#!/bin/bash
#SBATCH --job-name=rMD_pten
#SBATCH --output=slurm_out/fold_1nm_6ns_ext.slurm
#SBATCH --nodelist=jimi
# #SBATCH --cpus-per-task=8

#python3 Simulation_unfolding.py
python3 extend_folding.py